import { MessageSquare, Zap, FileText, Database, FileCode, Table, Settings, BarChart3, Zap as ZapIcon, BookOpen, AlertTriangle, GitBranch, Mail, Share2, User, Newspaper, ShoppingBag, FileText as FileTextIcon, Briefcase, PenSquare } from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category: string;
  href: string;
}

export const tools: Tool[] = [
  {
    id: "chat",
    name: "AI Chat",
    description: "Chat with AI models for general assistance and conversation.",
    icon: MessageSquare,
    category: "General",
    href: "/tools/chat",
  },
  {
    id: "regex",
    name: "Regex Generator",
    description: "Generate and test regular expressions with explanations.",
    icon: Zap,
    category: "Development",
    href: "/tools/regex",
  },
  {
    id: "summarizer",
    name: "Text Summarizer",
    description: "Summarize long text content with customizable length and style.",
    icon: FileText,
    category: "Text Processing",
    href: "/tools/summarizer",
  },
  {
    id: "sql-generator",
    name: "SQL Query Generator",
    description: "Generate SQL queries from natural language with optimization suggestions.",
    icon: Database,
    category: "Development",
    href: "/tools/sql-generator",
  },
  {
    id: "api-docs-generator",
    name: "API Documentation Generator",
    description: "Generate OpenAPI/Swagger documentation from code.",
    icon: FileCode,
    category: "Development",
    href: "/tools/api-docs-generator",
  },
  {
    id: "schema-designer",
    name: "Database Schema Designer",
    description: "Create database schemas from requirements with relationships and indexes.",
    icon: Table,
    category: "Development",
    href: "/tools/schema-designer",
  },
  {
    id: "env-generator",
    name: "Environment Config Generator",
    description: "Create .env templates with documentation and validation.",
    icon: Settings,
    category: "Development",
    href: "/tools/env-generator",
  },
  {
    id: "complexity-analyzer",
    name: "Code Complexity Analyzer",
    description: "Analyze code complexity and suggest simplifications.",
    icon: BarChart3,
    category: "Development",
    href: "/tools/complexity-analyzer",
  },
  {
    id: "performance-optimizer",
    name: "Performance Optimizer",
    description: "Suggest performance improvements for code with benchmarks.",
    icon: ZapIcon,
    category: "Development",
    href: "/tools/performance-optimizer",
  },
  {
    id: "readme-generator",
    name: "README Generator",
    description: "Create comprehensive README files from codebases.",
    icon: BookOpen,
    category: "Development",
    href: "/tools/readme-generator",
  },
  {
    id: "error-decoder",
    name: "Error Message Decoder",
    description: "Explain and suggest fixes for error messages with code examples.",
    icon: AlertTriangle,
    category: "Development",
    href: "/tools/error-decoder",
  },
  {
    id: "pr-message-writer",
    name: "Git PR Message Writer",
    description: "Generate pull request descriptions from commit history with testing notes.",
    icon: GitBranch,
    category: "Development",
    href: "/tools/pr-message-writer",
  },
  {
    id: "email-template-generator",
    name: "Email Template Generator",
    description: "Create professional email templates with customizable tone and format.",
    icon: Mail,
    category: "Communication",
    href: "/tools/email-template-generator",
  },
  {
    id: "social-media-post-generator",
    name: "Social Media Post Generator",
    description: "Create engaging social media content with platform-specific optimizations.",
    icon: Share2,
    category: "Marketing",
    href: "/tools/social-media-post-generator",
  },
  {
    id: "contact-card-generator",
    name: "Contact Card Generator",
    description: "Convert contact info to vCard format with QR codes and import instructions.",
    icon: User,
    category: "Productivity",
    href: "/tools/contact-card-generator",
  },
  {
    id: "blog-post-generator",
    name: "Blog Post Generator",
    description: "Create SEO-optimized blog posts from topics with outlines and keywords.",
    icon: PenSquare,
    category: "Text & Content Creation",
    href: "/tools/blog-post-generator",
  },
  {
    id: "press-release-writer",
    name: "Press Release Writer",
    description: "Generate professional press releases for company announcements and news.",
    icon: Newspaper,
    category: "Text & Content Creation",
    href: "/tools/press-release-writer",
  },
  {
    id: "product-description-writer",
    name: "Product Description Writer",
    description: "Create compelling product descriptions with features, benefits, and SEO.",
    icon: ShoppingBag,
    category: "Text & Content Creation",
    href: "/tools/product-description-writer",
  },
  {
    id: "resume-builder",
    name: "Resume Builder",
    description: "Generate tailored resumes from experience data with ATS optimization.",
    icon: Briefcase,
    category: "Text & Content Creation",
    href: "/tools/resume-builder",
  },
  {
    id: "cover-letter-generator",
    name: "Cover Letter Generator",
    description: "Create personalized cover letters for job applications with key selling points.",
    icon: FileTextIcon,
    category: "Text & Content Creation",
    href: "/tools/cover-letter-generator",
  },
];
