import { MessageSquare, Zap, FileText, Database, FileCode, Table, Settings, BarChart3, Zap as ZapIcon, BookOpen, AlertTriangle, GitBranch, Mail, Share2, User, Newspaper, ShoppingBag, FileText as FileTextIcon, Briefcase, PenSquare, Award, FileText as FileTextIcon2, Calendar, Type, Search, Palette, Sparkles, Monitor, Building2, Type as TypeIcon, Image, TrendingUp, FileText as FileTextIcon3, Palette as PaletteIcon, BarChart3 as BarChart3Icon, LayoutDashboard, DollarSign, Map as MapIcon, BookOpen as BookOpenIcon, ClipboardList, MessageCircle, BarChart, TrendingUp as TrendingUpIcon, FileText as FileTextIcon4, CheckCircle, FileText as FileTextIcon5, FileText as FileTextIcon6, Lightbulb } from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category: string;
  href: string;
}

export const tools: Tool[] = [
  {
    id: "chat",
    name: "AI Chat",
    description: "Chat with AI models for general assistance and conversation.",
    icon: MessageSquare,
    category: "General",
    href: "/tools/chat",
  },
  {
    id: "regex",
    name: "Regex Generator",
    description: "Generate and test regular expressions with explanations.",
    icon: Zap,
    category: "Development",
    href: "/tools/regex",
  },
  {
    id: "summarizer",
    name: "Text Summarizer",
    description: "Summarize long text content with customizable length and style.",
    icon: FileText,
    category: "Text Processing",
    href: "/tools/summarizer",
  },
  {
    id: "sql-generator",
    name: "SQL Query Generator",
    description: "Generate SQL queries from natural language with optimization suggestions.",
    icon: Database,
    category: "Development",
    href: "/tools/sql-generator",
  },
  {
    id: "api-docs-generator",
    name: "API Documentation Generator",
    description: "Generate OpenAPI/Swagger documentation from code.",
    icon: FileCode,
    category: "Development",
    href: "/tools/api-docs-generator",
  },
  {
    id: "schema-designer",
    name: "Database Schema Designer",
    description: "Create database schemas from requirements with relationships and indexes.",
    icon: Table,
    category: "Development",
    href: "/tools/schema-designer",
  },
  {
    id: "env-generator",
    name: "Environment Config Generator",
    description: "Create .env templates with documentation and validation.",
    icon: Settings,
    category: "Development",
    href: "/tools/env-generator",
  },
  {
    id: "complexity-analyzer",
    name: "Code Complexity Analyzer",
    description: "Analyze code complexity and suggest simplifications.",
    icon: BarChart3,
    category: "Development",
    href: "/tools/complexity-analyzer",
  },
  {
    id: "performance-optimizer",
    name: "Performance Optimizer",
    description: "Suggest performance improvements for code with benchmarks.",
    icon: ZapIcon,
    category: "Development",
    href: "/tools/performance-optimizer",
  },
  {
    id: "readme-generator",
    name: "README Generator",
    description: "Create comprehensive README files from codebases.",
    icon: BookOpen,
    category: "Development",
    href: "/tools/readme-generator",
  },
  {
    id: "error-decoder",
    name: "Error Message Decoder",
    description: "Explain and suggest fixes for error messages with code examples.",
    icon: AlertTriangle,
    category: "Development",
    href: "/tools/error-decoder",
  },
  {
    id: "pr-message-writer",
    name: "Git PR Message Writer",
    description: "Generate pull request descriptions from commit history with testing notes.",
    icon: GitBranch,
    category: "Development",
    href: "/tools/pr-message-writer",
  },
  {
    id: "email-template-generator",
    name: "Email Template Generator",
    description: "Create professional email templates with customizable tone and format.",
    icon: Mail,
    category: "Communication",
    href: "/tools/email-template-generator",
  },
  {
    id: "social-media-post-generator",
    name: "Social Media Post Generator",
    description: "Create engaging social media content with platform-specific optimizations.",
    icon: Share2,
    category: "Marketing",
    href: "/tools/social-media-post-generator",
  },
  {
    id: "contact-card-generator",
    name: "Contact Card Generator",
    description: "Convert contact info to vCard format with QR codes and import instructions.",
    icon: User,
    category: "Productivity",
    href: "/tools/contact-card-generator",
  },
  {
    id: "blog-post-generator",
    name: "Blog Post Generator",
    description: "Create SEO-optimized blog posts from topics with outlines and keywords.",
    icon: PenSquare,
    category: "Text & Content Creation",
    href: "/tools/blog-post-generator",
  },
  {
    id: "press-release-writer",
    name: "Press Release Writer",
    description: "Generate professional press releases for company announcements and news.",
    icon: Newspaper,
    category: "Text & Content Creation",
    href: "/tools/press-release-writer",
  },
  {
    id: "product-description-writer",
    name: "Product Description Writer",
    description: "Create compelling product descriptions with features, benefits, and SEO.",
    icon: ShoppingBag,
    category: "Text & Content Creation",
    href: "/tools/product-description-writer",
  },
  {
    id: "resume-builder",
    name: "Resume Builder",
    description: "Generate tailored resumes from experience data with ATS optimization.",
    icon: Briefcase,
    category: "Text & Content Creation",
    href: "/tools/resume-builder",
  },
  {
    id: "cover-letter-generator",
    name: "Cover Letter Generator",
    description: "Create personalized cover letters for job applications with key selling points.",
    icon: FileTextIcon,
    category: "Text & Content Creation",
    href: "/tools/cover-letter-generator",
  },
  {
    id: "grant-proposal-writer",
    name: "Grant Proposal Writer",
    description: "Generate funding proposals and applications with comprehensive documentation.",
    icon: Award,
    category: "Text & Content Creation",
    href: "/tools/grant-proposal-writer",
  },
  {
    id: "technical-documentation-writer",
    name: "Technical Documentation Writer",
    description: "Create user manuals and guides with comprehensive technical documentation.",
    icon: FileTextIcon2,
    category: "Text & Content Creation",
    href: "/tools/technical-documentation-writer",
  },
  {
    id: "content-calendar-planner",
    name: "Content Calendar Planner",
    description: "Plan and generate content schedules with strategic content planning.",
    icon: Calendar,
    category: "Text & Content Creation",
    href: "/tools/content-calendar-planner",
  },
  {
    id: "headline-generator",
    name: "Headline Generator",
    description: "Create attention-grabbing headlines and titles with SEO optimization.",
    icon: Type,
    category: "Text & Content Creation",
    href: "/tools/headline-generator",
  },
  {
    id: "meta-description-generator",
    name: "Meta Description Generator",
    description: "Create SEO meta descriptions with keyword optimization and CTR improvement.",
    icon: Search,
    category: "Text & Content Creation",
    href: "/tools/meta-description-generator",
  },
  {
    id: "newsletter-creator",
    name: "Newsletter Creator",
    description: "Generate engaging newsletter content with call-to-action and social links.",
    icon: Mail,
    category: "Text & Content Creation",
    href: "/tools/newsletter-creator",
  },
  {
    id: "script-writer",
    name: "Script Writer",
    description: "Create professional scripts for videos, presentations, and podcasts.",
    icon: FileTextIcon,
    category: "Text & Content Creation",
    href: "/tools/script-writer",
  },
  {
    id: "story-generator",
    name: "Story Generator",
    description: "Generate compelling stories with character development and dialogue.",
    icon: PenSquare,
    category: "Text & Content Creation",
    href: "/tools/story-generator",
  },
  {
    id: "logo-concept-generator",
    name: "Logo Concept Generator",
    description: "Generate logo concept ideas with typography and color suggestions.",
    icon: Sparkles,
    category: "Creative & Design",
    href: "/tools/logo-concept-generator",
  },
  {
    id: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Create harmonious color palettes with accessibility and theory explanations.",
    icon: Palette,
    category: "Creative & Design",
    href: "/tools/color-palette-generator",
  },
  {
    id: "ui-ux-copy-generator",
    name: "UI/UX Copy Generator",
    description: "Generate microcopy for interfaces with user-friendly messaging.",
    icon: Monitor,
    category: "Creative & Design",
    href: "/tools/ui-ux-copy-generator",
  },
  {
    id: "brand-name-generator",
    name: "Brand Name Generator",
    description: "Create unique brand and product names with domain and trademark considerations.",
    icon: Sparkles,
    category: "Creative & Design",
    href: "/tools/brand-name-generator",
  },
  {
    id: "design-brief-generator",
    name: "Design Brief Generator",
    description: "Create comprehensive design briefs with technical specifications and timelines.",
    icon: FileTextIcon,
    category: "Creative & Design",
    href: "/tools/design-brief-generator",
  },
  {
    id: "business-plan-generator",
    name: "Business Plan Generator",
    description: "Create comprehensive business plans with financial projections and market analysis.",
    icon: Building2,
    category: "Business & Analytics",
    href: "/tools/business-plan-generator",
  },
  {
    id: "typography-pairer",
    name: "Typography Pairer",
    description: "Suggest font combinations for designs with web and print alternatives.",
    icon: TypeIcon,
    category: "Creative & Design",
    href: "/tools/typography-pairer",
  },
  {
    id: "icon-description-generator",
    name: "Icon Description Generator",
    description: "Generate detailed descriptions for icon creation with technical specifications.",
    icon: Image,
    category: "Creative & Design",
    href: "/tools/icon-description-generator",
  },
  {
    id: "swot-analysis-generator",
    name: "SWOT Analysis Generator",
    description: "Generate strategic analysis frameworks with detailed insights and action plans.",
    icon: TrendingUp,
    category: "Business & Analytics",
    href: "/tools/swot-analysis-generator",
  },
  {
    id: "style-guide-generator",
    name: "Style Guide Generator",
    description: "Create comprehensive brand style guides with design standards and guidelines.",
    icon: FileTextIcon3,
    category: "Creative & Design",
    href: "/tools/style-guide-generator",
  },
  {
    id: "creative-brief-writer",
    name: "Creative Brief Writer",
    description: "Generate comprehensive creative campaign briefs with strategic direction.",
    icon: FileTextIcon2,
    category: "Creative & Design",
    href: "/tools/creative-brief-writer",
  },
  {
    id: "art-prompt-generator",
    name: "Art Prompt Generator",
    description: "Create detailed art prompts with visual descriptions and technical specifications.",
    icon: PaletteIcon,
    category: "Creative & Design",
    href: "/tools/art-prompt-generator",
  },
  {
    id: "market-research-synthesizer",
    name: "Market Research Synthesizer",
    description: "Analyze and synthesize market data with competitive analysis and insights.",
    icon: BarChart3Icon,
    category: "Business & Analytics",
    href: "/tools/market-research-synthesizer",
  },
  {
    id: "financial-report-summarizer",
    name: "Financial Report Summarizer",
    description: "Summarize financial statements with key insights and strategic recommendations.",
    icon: BarChart3,
    category: "Business & Analytics",
    href: "/tools/financial-report-summarizer",
  },
  {
    id: "kpi-dashboard-designer",
    name: "KPI Dashboard Designer",
    description: "Design metrics tracking frameworks with key performance indicators and visualizations.",
    icon: LayoutDashboard,
    category: "Business & Analytics",
    href: "/tools/kpi-dashboard-designer",
  },
  {
    id: "risk-assessment-tool",
    name: "Risk Assessment Tool",
    description: "Identify and analyze business risks with mitigation strategies and monitoring frameworks.",
    icon: AlertTriangle,
    category: "Business & Analytics",
    href: "/tools/risk-assessment-tool",
  },
  {
    id: "roi-calculator",
    name: "ROI Calculator",
    description: "Calculate and explain return on investment with detailed analysis and recommendations.",
    icon: TrendingUp,
    category: "Business & Analytics",
    href: "/tools/roi-calculator",
  },
  {
    id: "budget-planner",
    name: "Budget Planner",
    description: "Create detailed budget breakdowns with forecasting and financial planning guidance.",
    icon: BarChart3,
    category: "Business & Analytics",
    href: "/tools/budget-planner",
  },
  {
    id: "pricing-strategy-generator",
    name: "Pricing Strategy Generator",
    description: "Develop competitive pricing models with market analysis and optimization strategies.",
    icon: DollarSign,
    category: "Business & Analytics",
    href: "/tools/pricing-strategy-generator",
  },
  {
    id: "customer-journey-mapper",
    name: "Customer Journey Mapper",
    description: "Map customer touchpoints and experiences with optimization recommendations.",
    icon: MapIcon,
    category: "Business & Analytics",
    href: "/tools/customer-journey-mapper",
  },
  {
    id: "literature-review-generator",
    name: "Literature Review Generator",
    description: "Synthesize academic papers and sources into comprehensive literature reviews.",
    icon: BookOpenIcon,
    category: "Research & Analysis",
    href: "/tools/literature-review-generator",
  },
  {
    id: "survey-designer",
    name: "Survey Designer",
    description: "Create comprehensive surveys and questionnaires for research and feedback.",
    icon: ClipboardList,
    category: "Research & Analysis",
    href: "/tools/survey-designer",
  },
  {
    id: "interview-question-generator",
    name: "Interview Question Generator",
    description: "Generate targeted interview questions for research and hiring.",
    icon: MessageCircle,
    category: "Research & Analysis",
    href: "/tools/interview-question-generator",
  },
  {
    id: "data-analysis-interpreter",
    name: "Data Analysis Interpreter",
    description: "Explain statistical analyses and data insights in plain language.",
    icon: BarChart,
    category: "Research & Analysis",
    href: "/tools/data-analysis-interpreter",
  },
  {
    id: "trend-analyzer",
    name: "Trend Analyzer",
    description: "Identify patterns in data and market trends with actionable insights.",
    icon: TrendingUpIcon,
    category: "Research & Analysis",
    href: "/tools/trend-analyzer",
  },
  {
    id: "citation-generator",
    name: "Citation Generator",
    description: "Generate proper citations in various academic formats.",
    icon: FileTextIcon4,
    category: "Research & Analysis",
    href: "/tools/citation-generator",
  },
  {
    id: "fact-checker",
    name: "Fact Checker",
    description: "Verify claims and provide source validation for research.",
    icon: CheckCircle,
    category: "Research & Analysis",
    href: "/tools/fact-checker",
  },
  {
    id: "research-proposal-writer",
    name: "Research Proposal Writer",
    description: "Create structured research proposals with methodology and objectives.",
    icon: FileTextIcon5,
    category: "Research & Analysis",
    href: "/tools/research-proposal-writer",
  },
  {
    id: "abstract-generator",
    name: "Abstract Generator",
    description: "Generate academic abstracts from research papers and content.",
    icon: FileTextIcon6,
    category: "Research & Analysis",
    href: "/tools/abstract-generator",
  },
  {
    id: "hypothesis-generator",
    name: "Hypothesis Generator",
    description: "Create testable hypotheses from research questions and observations.",
    icon: Lightbulb,
    category: "Research & Analysis",
    href: "/tools/hypothesis-generator",
  },
];
