export const STORAGE_KEYS = {
  API_KEY: "api-key",
  PREFERENCES: "preferences",
  TOOL_EXECUTIONS: "tool-executions",
  ACTIVE_EXECUTIONS: "active-executions",
  PINNED_TOOLS: "pinned-tools",
} as const;

export const TOOL_IDS = {
  CHAT: "chat",
  REGEX: "regex",
  SUMMARIZER: "summarizer",
  SQL_GENERATOR: "sql-generator",
  API_DOCS_GENERATOR: "api-docs-generator",
  SCHEMA_DESIGNER: "schema-designer",
  ENV_GENERATOR: "env-generator",
  COMPLEXITY_ANALYZER: "complexity-analyzer",
  PERFORMANCE_OPTIMIZER: "performance-optimizer",
  README_GENERATOR: "readme-generator",
  ERROR_DECODER: "error-decoder",
  PR_MESSAGE_WRITER: "pr-message-writer",
  EMAIL_TEMPLATE_GENERATOR: "email-template-generator",
  SOCIAL_MEDIA_POST_GENERATOR: "social-media-post-generator",
  CONTACT_CARD_GENERATOR: "contact-card-generator",
  BLOG_POST_GENERATOR: "blog-post-generator",
  PRESS_RELEASE_WRITER: "press-release-writer",
  PRODUCT_DESCRIPTION_WRITER: "product-description-writer",
  RESUME_BUILDER: "resume-builder",
  COVER_LETTER_GENERATOR: "cover-letter-generator",
  GRANT_PROPOSAL_WRITER: "grant-proposal-writer",
  TECHNICAL_DOCUMENTATION_WRITER: "technical-documentation-writer",
  CONTENT_CALENDAR_PLANNER: "content-calendar-planner",
  HEADLINE_GENERATOR: "headline-generator",
  META_DESCRIPTION_GENERATOR: "meta-description-generator",
  NEWSLETTER_CREATOR: "newsletter-creator",
  SCRIPT_WRITER: "script-writer",
  STORY_GENERATOR: "story-generator",
  LOGO_CONCEPT_GENERATOR: "logo-concept-generator",
  COLOR_PALETTE_GENERATOR: "color-palette-generator",
  UI_UX_COPY_GENERATOR: "ui-ux-copy-generator",
  BRAND_NAME_GENERATOR: "brand-name-generator",
  DESIGN_BRIEF_GENERATOR: "design-brief-generator",
  BUSINESS_PLAN_GENERATOR: "business-plan-generator",
  TYPOGRAPHY_PAIRER: "typography-pairer",
  ICON_DESCRIPTION_GENERATOR: "icon-description-generator",
  SWOT_ANALYSIS_GENERATOR: "swot-analysis-generator",
  STYLE_GUIDE_GENERATOR: "style-guide-generator",
  CREATIVE_BRIEF_WRITER: "creative-brief-writer",
  ART_PROMPT_GENERATOR: "art-prompt-generator",
  MARKET_RESEARCH_SYNTHESIZER: "market-research-synthesizer",
  FINANCIAL_REPORT_SUMMARIZER: "financial-report-summarizer",
  KPI_DASHBOARD_DESIGNER: "kpi-dashboard-designer",
  RISK_ASSESSMENT_TOOL: "risk-assessment-tool",
  ROI_CALCULATOR: "roi-calculator",
  BUDGET_PLANNER: "budget-planner",
  PRICING_STRATEGY_GENERATOR: "pricing-strategy-generator",
  CUSTOMER_JOURNEY_MAPPER: "customer-journey-mapper",
  COMPETITOR_ANALYSIS_TOOL: "competitor-analysis-tool",
  SALES_PITCH_GENERATOR: "sales-pitch-generator",
  LITERATURE_REVIEW_GENERATOR: "literature-review-generator",
  SURVEY_DESIGNER: "survey-designer",
  INTERVIEW_QUESTION_GENERATOR: "interview-question-generator",
  DATA_ANALYSIS_INTERPRETER: "data-analysis-interpreter",
  TREND_ANALYZER: "trend-analyzer",
  CITATION_GENERATOR: "citation-generator",
  FACT_CHECKER: "fact-checker",
  RESEARCH_PROPOSAL_WRITER: "research-proposal-writer",
  ABSTRACT_GENERATOR: "abstract-generator",
  HYPOTHESIS_GENERATOR: "hypothesis-generator",
  QUIZ_GENERATOR: "quiz-generator",
  LESSON_PLAN_CREATOR: "lesson-plan-creator",
  FLASHCARD_GENERATOR: "flashcard-generator",
  STUDY_GUIDE_GENERATOR: "study-guide-generator",
  CURRICULUM_DESIGNER: "curriculum-designer",
  LEARNING_OBJECTIVE_WRITER: "learning-objective-writer",
  ASSESSMENT_RUBRIC_CREATOR: "assessment-rubric-creator",
  SYLLABUS_GENERATOR: "syllabus-generator",
  MEETING_MINUTES_GENERATOR: "meeting-minutes-generator",
  TASK_PRIORITIZER: "task-prioritizer",
  PROJECT_TIMELINE_CREATOR: "project-timeline-creator",
  GOAL_SETTING_ASSISTANT: "goal-setting-assistant",
  HABIT_TRACKER_DESIGNER: "habit-tracker-designer",
  DAILY_SCHEDULE_OPTIMIZER: "daily-schedule-optimizer",
  DECISION_MATRIX_CREATOR: "decision-matrix-creator",
  PROCESS_DOCUMENTER: "process-documenter",
  SOP_GENERATOR: "sop-generator",
  WORKFLOW_DESIGNER: "workflow-designer",
} as const;

import { DEFAULT_MODEL_ID } from "../models";

export const DEFAULT_PREFERENCES = {
  defaultModel: DEFAULT_MODEL_ID,
  theme: "system" as const,
  sidebarCollapsed: false,
  toolSettings: {},
};
